POST http://localhost/graphql HTTP/1.1
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
    login(email:"admin@localhost.com",password:"password") {email,name,token}
}
###
POST http://localhost/graphql HTTP/1.1
Content-Type: application/json
X-REQUEST-TYPE: GraphQL
Authorization: Bearer 2|1j4cFyo1QhzPWTT4MqB3jcHSnm3KNwY3hWgIWisj

mutation {
    logout
}
###
POST http://localhost/graphql HTTP/1.1
Content-Type: application/json
Authorization: Bearer 2|1j4cFyo1QhzPWTT4MqB3jcHSnm3KNwY3hWgIWisj
X-REQUEST-TYPE: GraphQL
# X-CSRF-TOKEN:eyJpdiI6ImN6RHBvdlFNZlFDZ2N4cU40RHIvMWc9PSIsInZhbHVlIjoiVHlZR2xDMGdScHJOUnZXbEk2T1hQdXR1RkxMUWFxSDVqNHEzRVd0d3VsTGgwT3FFK1ZxM3ZwUW9qVEQ4dDlQQnV0UXVqQWc3TXA0WGp5c0JGWnJMQ2xNeHVVUmZTbXN2TTFVb3pjanAwLy8zTWlCVjg0cndpaW9ycXpYSkRFQzIiLCJtYWMiOiJhMjNjYzEyMmNlMmM2YzM0OTkzMDZjZGUwNTdmNDRlMDdlM2EyOGY2ZGI3ZDYwYzI0OWU4YmE4OGU4ZmY5N2NjIn0%3D; expires=Tue, 27-Apr-2021 20:45:39 GMT; Max-Age=7200; path=/; domain=localhost; samesite=lax,laravel_session=eyJpdiI6Ik8zU282eHZjUGJnWXZEdDBkeEVOK3c9PSIsInZhbHVlIjoiNTlHY2U2Vk5CYTZqc3cwR0pvbzV6Z1dHQ2pFQXNSMi9VK3owL0hKZ2F2dlM3dmxoRVk1aGQyRmF4c3RRY3RoQkhsQ2gwU0JPWk5VeHFuYWVXUGJNWHc3emF2ME1yZ2tzVlRGbi9DQ3ZuUnNvancvcjFDak05Y3dNcW12ejdTamwiLCJtYWMiOiI0ODk2NDI4MTliNTM5N2JlYzZiYTkxYzBhN2VmYTBkNTZkNDA3MjNkYjc1YTRhZTNhMTAwZWYyOTMxYmU0ZGI3In0%3D; expires=Tue, 27-Apr-2021 20:45:39 GMT; Max-Age=7200; path=/; domain=localhost; httponly; samesite=lax

query {
    customers {name}
}

###
GET http://localhost/sanctum/csrf-cookie 

###
POST http://localhost/tokens/create


